apiVersion: apps/v1
kind: Deployment
metadata:
  name: timeoff-deployment
  labels:
    app: timeoff
spec:
  replicas: 1
  selector:
    matchLabels:
      app: timeoff
  template:
    metadata:
      labels:
        app: timeoff
    spec:
      containers:
      - name: timeoff
        image: jamal1710/timeoff:v1
        ports:
        - containerPort: 3000  # Assuming your application listens on port 80
