apiVersion: v1
kind: Service
metadata:
  name: timeoff-service
spec:
  selector:
    app: timeoff
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000  # The port on the container that the service should direct traffic to
